
import java.util.List;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lenovo
 */
public class Gui extends javax.swing.JPanel {

    private static boolean begin = false;
    private static boolean isTempGr;
    private static boolean isPulsGr;
    private static double maxTempGr;
    private static double minTempGr;
    private static double maxPulsGr;
    private static double minPulsGr;
    //rivate static boolean isMax = false;
    //private static boolean isMin = false;
    private static JFrame tempGrafFrame = null;
    private static JFrame pulsGrafFrame = null;
    List<Double> data;

    /**
     * Creates new form Gui
     */
    /*konstruktør der bl.a. skjuler stop og graf knap*/
    public Gui() {
        initComponents();
        tempGrafKnap.setVisible(false);
        pulsGrafKnap.setVisible(false);
        stopKnap.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minTemp = new javax.swing.JTextField();
        maxTemp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tempGrafKnap = new javax.swing.JButton();
        tempLabelInfo = new javax.swing.JLabel();
        startKnap = new javax.swing.JButton();
        stopKnap = new javax.swing.JButton();
        tempCheckBox = new javax.swing.JCheckBox();
        pulsCheckBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        tempLabel = new javax.swing.JLabel();
        tempAlarmLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pulsGrafKnap = new javax.swing.JButton();
        pulsLabelInfo = new javax.swing.JLabel();
        pulsLabel = new javax.swing.JLabel();
        pulsAlarmLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        minPuls = new javax.swing.JTextField();
        maxPuls = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        minTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTempActionPerformed(evt);
            }
        });

        maxTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxTempActionPerformed(evt);
            }
        });

        jLabel1.setText("Max temp");

        jLabel2.setText("Min temp");

        tempGrafKnap.setText("Vis graf for temperatur");
        tempGrafKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempGrafKnapActionPerformed(evt);
            }
        });

        tempLabelInfo.setText("Temperaturværdi:");

        startKnap.setText("Start Måling");
        startKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startKnapActionPerformed(evt);
            }
        });

        stopKnap.setText("Stop Måling");
        stopKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopKnapActionPerformed(evt);
            }
        });

        tempCheckBox.setSelected(true);
        tempCheckBox.setText("Temperatur");
        tempCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempCheckBoxActionPerformed(evt);
            }
        });

        pulsCheckBox.setSelected(true);
        pulsCheckBox.setText("Puls");

        tempLabel.setText("(temperaturværdi)");

        tempAlarmLabel.setText("(Alarm)");

        pulsGrafKnap.setText("Vis graf for puls");
        pulsGrafKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsGrafKnapActionPerformed(evt);
            }
        });

        pulsLabelInfo.setText("Pulsværdi:");

        pulsLabel.setText("(pulsværdi)");

        pulsAlarmLabel.setText("(Alarm)");

        jLabel3.setText("Indtast grænseværdier for temperaturmåling:");

        jLabel4.setText("Indtast grænseværdier for pulsmåling:");

        minPuls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minPulsActionPerformed(evt);
            }
        });

        maxPuls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPulsActionPerformed(evt);
            }
        });

        jLabel5.setText("Max puls");

        jLabel6.setText("Min puls");

        jLabel7.setText("Vælg sensortype:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pulsGrafKnap)
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pulsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pulsAlarmLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pulsLabelInfo)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(tempGrafKnap)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempLabelInfo)
                                    .addComponent(tempLabel))
                                .addGap(88, 88, 88)
                                .addComponent(tempAlarmLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopKnap)
                            .addComponent(startKnap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxPuls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minPuls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempCheckBox)
                            .addComponent(jLabel7)
                            .addComponent(pulsCheckBox))
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startKnap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopKnap))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tempCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsCheckBox)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempGrafKnap)
                    .addComponent(tempLabelInfo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tempLabel)
                    .addComponent(tempAlarmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulsGrafKnap)
                            .addComponent(pulsLabelInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulsLabel)
                            .addComponent(pulsAlarmLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxPuls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minPuls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void minTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minTempActionPerformed

    private void tempGrafKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempGrafKnapActionPerformed
        /*ved tryk på graf knappen åbnes nyt vindue der tegner grafen vha. TegnePanel*/
        tempGrafFrame = new JFrame("Temperatur Graf");
        tempGrafFrame.setVisible(true);
        tempGrafFrame.setSize(600, 400);
        tempGrafFrame.add(new TegnePanel());
    }//GEN-LAST:event_tempGrafKnapActionPerformed

    private void maxTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxTempActionPerformed

    private void startKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startKnapActionPerformed
        stopKnap.setVisible(true);
        startKnap.setVisible(false);
        if (tempCheckBox.isSelected()) {
            isTempGr = false;
            tempGrafKnap.setVisible(true);
            try {
                maxTempGr = Double.parseDouble(maxTemp.getText());
            } catch (NumberFormatException n) {
                maxTempGr = 39.0;
              maxTemp.setText(String.valueOf(maxTempGr));
              isTempGr = true;
            }
            try {
                minTempGr = Double.parseDouble(minTemp.getText());
            } catch (NumberFormatException n) {
                minTempGr = 35.0;
                minTemp.setText(String.valueOf(minTempGr));
                isTempGr = true;
            }
            if(isTempGr){
                //dialog eller besked
            }

        }
        
        if (pulsCheckBox.isSelected()) {
            isPulsGr = false;
            pulsGrafKnap.setVisible(true);
            try {
                maxPulsGr = Double.parseDouble(maxPuls.getText());
            } catch (NumberFormatException n) {
                maxPulsGr = 120.0;
              maxPuls.setText(String.valueOf(maxPulsGr));
              isPulsGr =true;
            }
            try {
                minPulsGr = Double.parseDouble(minPuls.getText());
            } catch (NumberFormatException n) {
                minPulsGr = 50.0;
                minPuls.setText(String.valueOf(minPulsGr));
                isPulsGr =true;
            }
            if(isPulsGr){
                //dialog eller besked
            }

        }

        /*ved tryk på startnappen: skjules startknappen og graf + stop knap vises*/
 /*vi tester hvorvidt der indtastet grænseværdier, hvis ikke informerer vi brugeren
        *og grænseværdierne sættes til standardværdier: 39 og 35*/
 /*den boolske værdi der fortæller hvorvidt der er trykket på starknappen sættes til sand
        *så ved Examination at målingen er startet*/
        setStartet(true);
    }//GEN-LAST:event_startKnapActionPerformed

    private void stopKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopKnapActionPerformed
        /*ved tryk på stopknappen: skjules stop og graf knappen + startknappen vises igen*/
        startKnap.setVisible(true);
        stopKnap.setVisible(false);
        tempGrafKnap.setVisible(false);
        pulsGrafKnap.setVisible(false);
        /*den boolske værdi der fortæller hvorvidt der er trykket på starknappen sættes til falsk
        *så ved Examination at målingen er stoppet*/
        setStartet(false);
        
    }//GEN-LAST:event_stopKnapActionPerformed

    private void tempCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempCheckBoxActionPerformed

    private void minPulsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minPulsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minPulsActionPerformed

    private void maxPulsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPulsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxPulsActionPerformed

    private void pulsGrafKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsGrafKnapActionPerformed
        pulsGrafFrame = new JFrame("Puls Graf");
        pulsGrafFrame.setVisible(true);
        pulsGrafFrame.setSize(600, 400);
        pulsGrafFrame.add(new TegnePanel());
    }//GEN-LAST:event_pulsGrafKnapActionPerformed

    /*de følgende syv metoder, er metoder vi laver for at kunne ændre på gui fra Examination*/
 /*metode, der opdaterer temperaturværdien på gui og kalder repaint på grafen således at måling også vises på grafen*/
    public void setTemp(double temp) {
        tempLabel.setText("" + temp + " C");
        if (tempGrafFrame != null) {

            tempGrafFrame.repaint();
        }
    }
    
    public void setPuls(double puls) {
        pulsLabel.setText("" + puls + " BPM");
        if (pulsGrafFrame != null) {

            pulsGrafFrame.repaint();
        }
    }

    /*metode, der nustiller alarm beskeden*/
    public void resetTempAlarm() {
        tempAlarmLabel.setText("");
    }
    
     public void resetPulsAlarm() {
        pulsAlarmLabel.setText("");
    }


    /*metode, der viser alarm besked på gui*/
    public void setTempAlarm() {
        tempAlarmLabel.setText("ALARM: grænseværdi overskredet");
    }
    
    public void setPulsAlarm() {
        pulsAlarmLabel.setText("ALARM: grænseværdi overskredet");
    }

    /*metode der sætter den boolsk værdi, der fortæller om vi er startet eller ej*/
    public void setStartet(boolean value) {
        begin = value;
    }
    /*metode der via en boolsk værdi fortæller om vi er startet*/
    public boolean isStartet() {
        return begin;
    }

    /*metode der returnerer maximumsværdien*/
    public double getTempMax() {
        return maxTempGr;
    }

    public double getPulsMax() {
        return maxPulsGr;
    }
    /*metode, der returnerer minimumsværdien*/
    public double getTempMin() {
        return minTempGr;
    }
    
    public double getPulsMin() {
        return minPulsGr;
    }
    
    public boolean isTemp(){
        return tempCheckBox.isSelected();
    }
    
    public boolean isPuls(){
        return pulsCheckBox.isSelected();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maxPuls;
    private javax.swing.JTextField maxTemp;
    private javax.swing.JTextField minPuls;
    private javax.swing.JTextField minTemp;
    private javax.swing.JLabel pulsAlarmLabel;
    private javax.swing.JCheckBox pulsCheckBox;
    private javax.swing.JButton pulsGrafKnap;
    private javax.swing.JLabel pulsLabel;
    private javax.swing.JLabel pulsLabelInfo;
    private javax.swing.JButton startKnap;
    private javax.swing.JButton stopKnap;
    private javax.swing.JLabel tempAlarmLabel;
    private javax.swing.JCheckBox tempCheckBox;
    private javax.swing.JButton tempGrafKnap;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel tempLabelInfo;
    // End of variables declaration//GEN-END:variables
}
